### ISSUE TITLE
Add additional sanity checks on the whole DKG process

### ISSUE THREAD

**Issue by Nashtare** [topos-protocol/ice-frost#30]
Related to the item mentioned in #28, we would probably need additional sanity checks on the resharing phase.
There also needs to be a clear line drawn between what the protocol enforces, and what is expected to be done outside of this library (for instance the use of authenticated broadcast mechanism is explicitly required externally). 

- [x] resharing from a single party (part of #29)
- [x] resharing to a single party (part of #29)
- [x] resharing from a non-ICE-FROST single individual (done in #36)
- [ ] ...
